---
title: "Entscheidungsbäume-Handout"
author: "Natalie Pilz und Caroline Schörghofer"
format:
  html:
    toc: true
    html-math-method: katex
    theme: cosmo
---

## Defintion
Ein Entscheidungsbaum ist eine grafische Darstellung bzw. ein Modell, das Entscheidungen und deren mögliche Konsequenzen darstellt. Er besteht aus Knoten, die Entscheidungen oder Ereignisse repräsentieren, und Zweigen, die die möglichen Ergebnisse oder Optionen darstellen. Entscheidungsbäume werden häufig in der Datenanalyse, im maschinellen Lernen und in der Entscheidungsfindung verwendet, um komplexe Probleme zu strukturieren und zu visualisieren.


## Aufbau
umgedrehter Baum: beginnt bei Wurzeln und verzweigt sich in Richtung Blätter
•	Wurzelknoten: Startpunkt des Entscheidungsbaums
•	Entscheidungsknoten: Stelle, wo Entscheidung getroffen wird
•	Zweige: Optionen/Bedingungen, die von Knoten ausgehen
•	Blattknoten: Endpunkt, die Ergebnis/Entscheidung darstellen
Darstellung in Diagrammen

## Arten von Entscheidungsbäumen
•	Klassifikationsbäume: kategorische Zielvariable (z.B. Ja/Nein) "Was ist es?"
•	Regressionsbäume: kontinuierliche Zielvariable (z.B. Preis, Temperatur) "Wie viel ist es?"
•	Entscheidungsbäume für Zeitreihen: Vorhersage von zeitabhängigen Daten
•	Random Forests: Ensemble von Entscheidungsbäumen zur Verbesserung der Vorhersagegenau "Schwarmintelligenz"

## Einsatzgebiete
•	Businessanalysen: Bewertung von Geschäftsideen
•	Medizin: Diagnoseunterstützung
•	Maschinelles Lernen: Klassifikation in Entscheidungsmodelle
•	Softwareentwicklung: Steuerung von Abläufen/Benutzer
besonders in der KI genutzt

## Darstellung
!(Root-Node.gif){width="50%" fig-align="center"}
